//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NvdBKGK_lession07.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nvdSinhVien
    {
        public string NvdMaSV { get; set; }
        public string NvdHoSV { get; set; }
        public string NvdTenSV { get; set; }
        public Nullable<System.DateTime> NvdNgaySinh { get; set; }
        public Nullable<bool> NvdPhai { get; set; }
        public string NvdPhone { get; set; }
        public string NvdEmail { get; set; }
        public string NvdMaKH { get; set; }
    
        public virtual nvdKhoa nvdKhoa { get; set; }
    }
}
